services:
  postgres-service:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env.docker
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  authenticator-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authenticator
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    depends_on:
      - postgres-service

volumes:
  pgdata:
networks:
  authenticator:
    driver: bridge
